version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase"
    - mvn clean prepare-package war:exploded
  post_build:
    commands:
    - echo "Entered the post-build pase"
    - mv target/deploy ./
artifacts:
  files:
  - deploy/**/*
